### ISSUE TITLE
wyszukiwanie tych samych pozycji i merge

### ISSUE THREAD

**Issue by kisonar** [qweev/remanent-spring-boot#33]

**Comment by qweev** [comment]
o co w tym chodzi ?? jak to ma dzialac ? jakie kryterium ?definuje te same pozycje ? cena N + B + nazwa ?

**Comment by kisonar** [comment]
Ty to zdefiniowales. Wiec moze napisz jak to ma dzialac.
Takie info bylo w mailu co podelslaes. Nic wiecej

**Comment by kisonar** [comment]
Cena B i N ta sama. Nie ma znaczenia wiekszego opis. Po prostu merge

**Comment by kisonar** [comment]
Done
